version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: spartakiada_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spartakiada
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://spartakiada_user:admin@db/spartakiada
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: |
      sh -c "
        alembic upgrade head &&
        python -m app.utils.seed_data &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  postgres_data: